/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.goldgov.origin.modules.organization.api;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-08-20")
public class RpcOrganizationUserQuery implements org.apache.thrift.TBase<RpcOrganizationUserQuery, RpcOrganizationUserQuery._Fields>, java.io.Serializable, Cloneable, Comparable<RpcOrganizationUserQuery> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RpcOrganizationUserQuery");

  private static final org.apache.thrift.protocol.TField PAGING_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("pagingInfo", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField RESULT_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("resultList", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField SEARCH_ORG_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("searchOrgID", org.apache.thrift.protocol.TType.STRING, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new RpcOrganizationUserQueryStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new RpcOrganizationUserQueryTupleSchemeFactory();

  private com.goldgov.origin.core.service.rpc.RpcPagingInfo pagingInfo; // optional
  private java.util.List<RpcOrganization> resultList; // optional
  private java.lang.String searchOrgID; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PAGING_INFO((short)1, "pagingInfo"),
    RESULT_LIST((short)2, "resultList"),
    SEARCH_ORG_ID((short)3, "searchOrgID");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PAGING_INFO
          return PAGING_INFO;
        case 2: // RESULT_LIST
          return RESULT_LIST;
        case 3: // SEARCH_ORG_ID
          return SEARCH_ORG_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.PAGING_INFO,_Fields.RESULT_LIST,_Fields.SEARCH_ORG_ID};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PAGING_INFO, new org.apache.thrift.meta_data.FieldMetaData("pagingInfo", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.goldgov.origin.core.service.rpc.RpcPagingInfo.class)));
    tmpMap.put(_Fields.RESULT_LIST, new org.apache.thrift.meta_data.FieldMetaData("resultList", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, RpcOrganization.class))));
    tmpMap.put(_Fields.SEARCH_ORG_ID, new org.apache.thrift.meta_data.FieldMetaData("searchOrgID", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RpcOrganizationUserQuery.class, metaDataMap);
  }

  public RpcOrganizationUserQuery() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RpcOrganizationUserQuery(RpcOrganizationUserQuery other) {
    if (other.isSetPagingInfo()) {
      this.pagingInfo = new com.goldgov.origin.core.service.rpc.RpcPagingInfo(other.pagingInfo);
    }
    if (other.isSetResultList()) {
      java.util.List<RpcOrganization> __this__resultList = new java.util.ArrayList<RpcOrganization>(other.resultList.size());
      for (RpcOrganization other_element : other.resultList) {
        __this__resultList.add(new RpcOrganization(other_element));
      }
      this.resultList = __this__resultList;
    }
    if (other.isSetSearchOrgID()) {
      this.searchOrgID = other.searchOrgID;
    }
  }

  public RpcOrganizationUserQuery deepCopy() {
    return new RpcOrganizationUserQuery(this);
  }

  @Override
  public void clear() {
    this.pagingInfo = null;
    this.resultList = null;
    this.searchOrgID = null;
  }

  public com.goldgov.origin.core.service.rpc.RpcPagingInfo getPagingInfo() {
    return this.pagingInfo;
  }

  public void setPagingInfo(com.goldgov.origin.core.service.rpc.RpcPagingInfo pagingInfo) {
    this.pagingInfo = pagingInfo;
  }

  public void unsetPagingInfo() {
    this.pagingInfo = null;
  }

  /** Returns true if field pagingInfo is set (has been assigned a value) and false otherwise */
  public boolean isSetPagingInfo() {
    return this.pagingInfo != null;
  }

  public void setPagingInfoIsSet(boolean value) {
    if (!value) {
      this.pagingInfo = null;
    }
  }

  public int getResultListSize() {
    return (this.resultList == null) ? 0 : this.resultList.size();
  }

  public java.util.Iterator<RpcOrganization> getResultListIterator() {
    return (this.resultList == null) ? null : this.resultList.iterator();
  }

  public void addToResultList(RpcOrganization elem) {
    if (this.resultList == null) {
      this.resultList = new java.util.ArrayList<RpcOrganization>();
    }
    this.resultList.add(elem);
  }

  public java.util.List<RpcOrganization> getResultList() {
    return this.resultList;
  }

  public void setResultList(java.util.List<RpcOrganization> resultList) {
    this.resultList = resultList;
  }

  public void unsetResultList() {
    this.resultList = null;
  }

  /** Returns true if field resultList is set (has been assigned a value) and false otherwise */
  public boolean isSetResultList() {
    return this.resultList != null;
  }

  public void setResultListIsSet(boolean value) {
    if (!value) {
      this.resultList = null;
    }
  }

  public java.lang.String getSearchOrgID() {
    return this.searchOrgID;
  }

  public void setSearchOrgID(java.lang.String searchOrgID) {
    this.searchOrgID = searchOrgID;
  }

  public void unsetSearchOrgID() {
    this.searchOrgID = null;
  }

  /** Returns true if field searchOrgID is set (has been assigned a value) and false otherwise */
  public boolean isSetSearchOrgID() {
    return this.searchOrgID != null;
  }

  public void setSearchOrgIDIsSet(boolean value) {
    if (!value) {
      this.searchOrgID = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case PAGING_INFO:
      if (value == null) {
        unsetPagingInfo();
      } else {
        setPagingInfo((com.goldgov.origin.core.service.rpc.RpcPagingInfo)value);
      }
      break;

    case RESULT_LIST:
      if (value == null) {
        unsetResultList();
      } else {
        setResultList((java.util.List<RpcOrganization>)value);
      }
      break;

    case SEARCH_ORG_ID:
      if (value == null) {
        unsetSearchOrgID();
      } else {
        setSearchOrgID((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case PAGING_INFO:
      return getPagingInfo();

    case RESULT_LIST:
      return getResultList();

    case SEARCH_ORG_ID:
      return getSearchOrgID();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case PAGING_INFO:
      return isSetPagingInfo();
    case RESULT_LIST:
      return isSetResultList();
    case SEARCH_ORG_ID:
      return isSetSearchOrgID();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof RpcOrganizationUserQuery)
      return this.equals((RpcOrganizationUserQuery)that);
    return false;
  }

  public boolean equals(RpcOrganizationUserQuery that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_pagingInfo = true && this.isSetPagingInfo();
    boolean that_present_pagingInfo = true && that.isSetPagingInfo();
    if (this_present_pagingInfo || that_present_pagingInfo) {
      if (!(this_present_pagingInfo && that_present_pagingInfo))
        return false;
      if (!this.pagingInfo.equals(that.pagingInfo))
        return false;
    }

    boolean this_present_resultList = true && this.isSetResultList();
    boolean that_present_resultList = true && that.isSetResultList();
    if (this_present_resultList || that_present_resultList) {
      if (!(this_present_resultList && that_present_resultList))
        return false;
      if (!this.resultList.equals(that.resultList))
        return false;
    }

    boolean this_present_searchOrgID = true && this.isSetSearchOrgID();
    boolean that_present_searchOrgID = true && that.isSetSearchOrgID();
    if (this_present_searchOrgID || that_present_searchOrgID) {
      if (!(this_present_searchOrgID && that_present_searchOrgID))
        return false;
      if (!this.searchOrgID.equals(that.searchOrgID))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetPagingInfo()) ? 131071 : 524287);
    if (isSetPagingInfo())
      hashCode = hashCode * 8191 + pagingInfo.hashCode();

    hashCode = hashCode * 8191 + ((isSetResultList()) ? 131071 : 524287);
    if (isSetResultList())
      hashCode = hashCode * 8191 + resultList.hashCode();

    hashCode = hashCode * 8191 + ((isSetSearchOrgID()) ? 131071 : 524287);
    if (isSetSearchOrgID())
      hashCode = hashCode * 8191 + searchOrgID.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(RpcOrganizationUserQuery other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetPagingInfo()).compareTo(other.isSetPagingInfo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPagingInfo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pagingInfo, other.pagingInfo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetResultList()).compareTo(other.isSetResultList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResultList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.resultList, other.resultList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSearchOrgID()).compareTo(other.isSetSearchOrgID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSearchOrgID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.searchOrgID, other.searchOrgID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("RpcOrganizationUserQuery(");
    boolean first = true;

    if (isSetPagingInfo()) {
      sb.append("pagingInfo:");
      if (this.pagingInfo == null) {
        sb.append("null");
      } else {
        sb.append(this.pagingInfo);
      }
      first = false;
    }
    if (isSetResultList()) {
      if (!first) sb.append(", ");
      sb.append("resultList:");
      if (this.resultList == null) {
        sb.append("null");
      } else {
        sb.append(this.resultList);
      }
      first = false;
    }
    if (isSetSearchOrgID()) {
      if (!first) sb.append(", ");
      sb.append("searchOrgID:");
      if (this.searchOrgID == null) {
        sb.append("null");
      } else {
        sb.append(this.searchOrgID);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (pagingInfo != null) {
      pagingInfo.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RpcOrganizationUserQueryStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RpcOrganizationUserQueryStandardScheme getScheme() {
      return new RpcOrganizationUserQueryStandardScheme();
    }
  }

  private static class RpcOrganizationUserQueryStandardScheme extends org.apache.thrift.scheme.StandardScheme<RpcOrganizationUserQuery> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RpcOrganizationUserQuery struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PAGING_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.pagingInfo = new com.goldgov.origin.core.service.rpc.RpcPagingInfo();
              struct.pagingInfo.read(iprot);
              struct.setPagingInfoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RESULT_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.resultList = new java.util.ArrayList<RpcOrganization>(_list8.size);
                RpcOrganization _elem9;
                for (int _i10 = 0; _i10 < _list8.size; ++_i10)
                {
                  _elem9 = new RpcOrganization();
                  _elem9.read(iprot);
                  struct.resultList.add(_elem9);
                }
                iprot.readListEnd();
              }
              struct.setResultListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // SEARCH_ORG_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.searchOrgID = iprot.readString();
              struct.setSearchOrgIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RpcOrganizationUserQuery struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.pagingInfo != null) {
        if (struct.isSetPagingInfo()) {
          oprot.writeFieldBegin(PAGING_INFO_FIELD_DESC);
          struct.pagingInfo.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.resultList != null) {
        if (struct.isSetResultList()) {
          oprot.writeFieldBegin(RESULT_LIST_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.resultList.size()));
            for (RpcOrganization _iter11 : struct.resultList)
            {
              _iter11.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.searchOrgID != null) {
        if (struct.isSetSearchOrgID()) {
          oprot.writeFieldBegin(SEARCH_ORG_ID_FIELD_DESC);
          oprot.writeString(struct.searchOrgID);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RpcOrganizationUserQueryTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RpcOrganizationUserQueryTupleScheme getScheme() {
      return new RpcOrganizationUserQueryTupleScheme();
    }
  }

  private static class RpcOrganizationUserQueryTupleScheme extends org.apache.thrift.scheme.TupleScheme<RpcOrganizationUserQuery> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RpcOrganizationUserQuery struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetPagingInfo()) {
        optionals.set(0);
      }
      if (struct.isSetResultList()) {
        optionals.set(1);
      }
      if (struct.isSetSearchOrgID()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetPagingInfo()) {
        struct.pagingInfo.write(oprot);
      }
      if (struct.isSetResultList()) {
        {
          oprot.writeI32(struct.resultList.size());
          for (RpcOrganization _iter12 : struct.resultList)
          {
            _iter12.write(oprot);
          }
        }
      }
      if (struct.isSetSearchOrgID()) {
        oprot.writeString(struct.searchOrgID);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RpcOrganizationUserQuery struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.pagingInfo = new com.goldgov.origin.core.service.rpc.RpcPagingInfo();
        struct.pagingInfo.read(iprot);
        struct.setPagingInfoIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.resultList = new java.util.ArrayList<RpcOrganization>(_list13.size);
          RpcOrganization _elem14;
          for (int _i15 = 0; _i15 < _list13.size; ++_i15)
          {
            _elem14 = new RpcOrganization();
            _elem14.read(iprot);
            struct.resultList.add(_elem14);
          }
        }
        struct.setResultListIsSet(true);
      }
      if (incoming.get(2)) {
        struct.searchOrgID = iprot.readString();
        struct.setSearchOrgIDIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

