/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.goldgov.origin.modules.organization.api;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-08-20")
public class RpcOrganizationPost implements org.apache.thrift.TBase<RpcOrganizationPost, RpcOrganizationPost._Fields>, java.io.Serializable, Cloneable, Comparable<RpcOrganizationPost> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RpcOrganizationPost");

  private static final org.apache.thrift.protocol.TField ORG_POST_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("orgPostID", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField POST_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("postName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField POST_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("postCode", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField ORGANIZATION_FIELD_DESC = new org.apache.thrift.protocol.TField("organization", org.apache.thrift.protocol.TType.STRUCT, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new RpcOrganizationPostStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new RpcOrganizationPostTupleSchemeFactory();

  private java.lang.String orgPostID; // optional
  private java.lang.String postName; // optional
  private java.lang.String postCode; // optional
  private RpcOrganization organization; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ORG_POST_ID((short)1, "orgPostID"),
    POST_NAME((short)2, "postName"),
    POST_CODE((short)3, "postCode"),
    ORGANIZATION((short)4, "organization");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ORG_POST_ID
          return ORG_POST_ID;
        case 2: // POST_NAME
          return POST_NAME;
        case 3: // POST_CODE
          return POST_CODE;
        case 4: // ORGANIZATION
          return ORGANIZATION;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.ORG_POST_ID,_Fields.POST_NAME,_Fields.POST_CODE,_Fields.ORGANIZATION};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ORG_POST_ID, new org.apache.thrift.meta_data.FieldMetaData("orgPostID", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.POST_NAME, new org.apache.thrift.meta_data.FieldMetaData("postName", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.POST_CODE, new org.apache.thrift.meta_data.FieldMetaData("postCode", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ORGANIZATION, new org.apache.thrift.meta_data.FieldMetaData("organization", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, RpcOrganization.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RpcOrganizationPost.class, metaDataMap);
  }

  public RpcOrganizationPost() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RpcOrganizationPost(RpcOrganizationPost other) {
    if (other.isSetOrgPostID()) {
      this.orgPostID = other.orgPostID;
    }
    if (other.isSetPostName()) {
      this.postName = other.postName;
    }
    if (other.isSetPostCode()) {
      this.postCode = other.postCode;
    }
    if (other.isSetOrganization()) {
      this.organization = new RpcOrganization(other.organization);
    }
  }

  public RpcOrganizationPost deepCopy() {
    return new RpcOrganizationPost(this);
  }

  @Override
  public void clear() {
    this.orgPostID = null;
    this.postName = null;
    this.postCode = null;
    this.organization = null;
  }

  public java.lang.String getOrgPostID() {
    return this.orgPostID;
  }

  public void setOrgPostID(java.lang.String orgPostID) {
    this.orgPostID = orgPostID;
  }

  public void unsetOrgPostID() {
    this.orgPostID = null;
  }

  /** Returns true if field orgPostID is set (has been assigned a value) and false otherwise */
  public boolean isSetOrgPostID() {
    return this.orgPostID != null;
  }

  public void setOrgPostIDIsSet(boolean value) {
    if (!value) {
      this.orgPostID = null;
    }
  }

  public java.lang.String getPostName() {
    return this.postName;
  }

  public void setPostName(java.lang.String postName) {
    this.postName = postName;
  }

  public void unsetPostName() {
    this.postName = null;
  }

  /** Returns true if field postName is set (has been assigned a value) and false otherwise */
  public boolean isSetPostName() {
    return this.postName != null;
  }

  public void setPostNameIsSet(boolean value) {
    if (!value) {
      this.postName = null;
    }
  }

  public java.lang.String getPostCode() {
    return this.postCode;
  }

  public void setPostCode(java.lang.String postCode) {
    this.postCode = postCode;
  }

  public void unsetPostCode() {
    this.postCode = null;
  }

  /** Returns true if field postCode is set (has been assigned a value) and false otherwise */
  public boolean isSetPostCode() {
    return this.postCode != null;
  }

  public void setPostCodeIsSet(boolean value) {
    if (!value) {
      this.postCode = null;
    }
  }

  public RpcOrganization getOrganization() {
    return this.organization;
  }

  public void setOrganization(RpcOrganization organization) {
    this.organization = organization;
  }

  public void unsetOrganization() {
    this.organization = null;
  }

  /** Returns true if field organization is set (has been assigned a value) and false otherwise */
  public boolean isSetOrganization() {
    return this.organization != null;
  }

  public void setOrganizationIsSet(boolean value) {
    if (!value) {
      this.organization = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case ORG_POST_ID:
      if (value == null) {
        unsetOrgPostID();
      } else {
        setOrgPostID((java.lang.String)value);
      }
      break;

    case POST_NAME:
      if (value == null) {
        unsetPostName();
      } else {
        setPostName((java.lang.String)value);
      }
      break;

    case POST_CODE:
      if (value == null) {
        unsetPostCode();
      } else {
        setPostCode((java.lang.String)value);
      }
      break;

    case ORGANIZATION:
      if (value == null) {
        unsetOrganization();
      } else {
        setOrganization((RpcOrganization)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ORG_POST_ID:
      return getOrgPostID();

    case POST_NAME:
      return getPostName();

    case POST_CODE:
      return getPostCode();

    case ORGANIZATION:
      return getOrganization();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ORG_POST_ID:
      return isSetOrgPostID();
    case POST_NAME:
      return isSetPostName();
    case POST_CODE:
      return isSetPostCode();
    case ORGANIZATION:
      return isSetOrganization();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof RpcOrganizationPost)
      return this.equals((RpcOrganizationPost)that);
    return false;
  }

  public boolean equals(RpcOrganizationPost that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_orgPostID = true && this.isSetOrgPostID();
    boolean that_present_orgPostID = true && that.isSetOrgPostID();
    if (this_present_orgPostID || that_present_orgPostID) {
      if (!(this_present_orgPostID && that_present_orgPostID))
        return false;
      if (!this.orgPostID.equals(that.orgPostID))
        return false;
    }

    boolean this_present_postName = true && this.isSetPostName();
    boolean that_present_postName = true && that.isSetPostName();
    if (this_present_postName || that_present_postName) {
      if (!(this_present_postName && that_present_postName))
        return false;
      if (!this.postName.equals(that.postName))
        return false;
    }

    boolean this_present_postCode = true && this.isSetPostCode();
    boolean that_present_postCode = true && that.isSetPostCode();
    if (this_present_postCode || that_present_postCode) {
      if (!(this_present_postCode && that_present_postCode))
        return false;
      if (!this.postCode.equals(that.postCode))
        return false;
    }

    boolean this_present_organization = true && this.isSetOrganization();
    boolean that_present_organization = true && that.isSetOrganization();
    if (this_present_organization || that_present_organization) {
      if (!(this_present_organization && that_present_organization))
        return false;
      if (!this.organization.equals(that.organization))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetOrgPostID()) ? 131071 : 524287);
    if (isSetOrgPostID())
      hashCode = hashCode * 8191 + orgPostID.hashCode();

    hashCode = hashCode * 8191 + ((isSetPostName()) ? 131071 : 524287);
    if (isSetPostName())
      hashCode = hashCode * 8191 + postName.hashCode();

    hashCode = hashCode * 8191 + ((isSetPostCode()) ? 131071 : 524287);
    if (isSetPostCode())
      hashCode = hashCode * 8191 + postCode.hashCode();

    hashCode = hashCode * 8191 + ((isSetOrganization()) ? 131071 : 524287);
    if (isSetOrganization())
      hashCode = hashCode * 8191 + organization.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(RpcOrganizationPost other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetOrgPostID()).compareTo(other.isSetOrgPostID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOrgPostID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.orgPostID, other.orgPostID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPostName()).compareTo(other.isSetPostName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPostName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.postName, other.postName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPostCode()).compareTo(other.isSetPostCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPostCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.postCode, other.postCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetOrganization()).compareTo(other.isSetOrganization());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOrganization()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.organization, other.organization);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("RpcOrganizationPost(");
    boolean first = true;

    if (isSetOrgPostID()) {
      sb.append("orgPostID:");
      if (this.orgPostID == null) {
        sb.append("null");
      } else {
        sb.append(this.orgPostID);
      }
      first = false;
    }
    if (isSetPostName()) {
      if (!first) sb.append(", ");
      sb.append("postName:");
      if (this.postName == null) {
        sb.append("null");
      } else {
        sb.append(this.postName);
      }
      first = false;
    }
    if (isSetPostCode()) {
      if (!first) sb.append(", ");
      sb.append("postCode:");
      if (this.postCode == null) {
        sb.append("null");
      } else {
        sb.append(this.postCode);
      }
      first = false;
    }
    if (isSetOrganization()) {
      if (!first) sb.append(", ");
      sb.append("organization:");
      if (this.organization == null) {
        sb.append("null");
      } else {
        sb.append(this.organization);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (organization != null) {
      organization.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RpcOrganizationPostStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RpcOrganizationPostStandardScheme getScheme() {
      return new RpcOrganizationPostStandardScheme();
    }
  }

  private static class RpcOrganizationPostStandardScheme extends org.apache.thrift.scheme.StandardScheme<RpcOrganizationPost> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RpcOrganizationPost struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ORG_POST_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.orgPostID = iprot.readString();
              struct.setOrgPostIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // POST_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.postName = iprot.readString();
              struct.setPostNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // POST_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.postCode = iprot.readString();
              struct.setPostCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // ORGANIZATION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.organization = new RpcOrganization();
              struct.organization.read(iprot);
              struct.setOrganizationIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RpcOrganizationPost struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.orgPostID != null) {
        if (struct.isSetOrgPostID()) {
          oprot.writeFieldBegin(ORG_POST_ID_FIELD_DESC);
          oprot.writeString(struct.orgPostID);
          oprot.writeFieldEnd();
        }
      }
      if (struct.postName != null) {
        if (struct.isSetPostName()) {
          oprot.writeFieldBegin(POST_NAME_FIELD_DESC);
          oprot.writeString(struct.postName);
          oprot.writeFieldEnd();
        }
      }
      if (struct.postCode != null) {
        if (struct.isSetPostCode()) {
          oprot.writeFieldBegin(POST_CODE_FIELD_DESC);
          oprot.writeString(struct.postCode);
          oprot.writeFieldEnd();
        }
      }
      if (struct.organization != null) {
        if (struct.isSetOrganization()) {
          oprot.writeFieldBegin(ORGANIZATION_FIELD_DESC);
          struct.organization.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RpcOrganizationPostTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RpcOrganizationPostTupleScheme getScheme() {
      return new RpcOrganizationPostTupleScheme();
    }
  }

  private static class RpcOrganizationPostTupleScheme extends org.apache.thrift.scheme.TupleScheme<RpcOrganizationPost> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RpcOrganizationPost struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetOrgPostID()) {
        optionals.set(0);
      }
      if (struct.isSetPostName()) {
        optionals.set(1);
      }
      if (struct.isSetPostCode()) {
        optionals.set(2);
      }
      if (struct.isSetOrganization()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetOrgPostID()) {
        oprot.writeString(struct.orgPostID);
      }
      if (struct.isSetPostName()) {
        oprot.writeString(struct.postName);
      }
      if (struct.isSetPostCode()) {
        oprot.writeString(struct.postCode);
      }
      if (struct.isSetOrganization()) {
        struct.organization.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RpcOrganizationPost struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.orgPostID = iprot.readString();
        struct.setOrgPostIDIsSet(true);
      }
      if (incoming.get(1)) {
        struct.postName = iprot.readString();
        struct.setPostNameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.postCode = iprot.readString();
        struct.setPostCodeIsSet(true);
      }
      if (incoming.get(3)) {
        struct.organization = new RpcOrganization();
        struct.organization.read(iprot);
        struct.setOrganizationIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

